In [47]:
import pandas as pd
import numpy as np

In [48]:
data = pd.read_csv('C:\\Users\\soura\\OneDrive\\Documents\\CS661_proj\\data\\weather_states.csv')

In [49]:
# bin 'temp' column
bins_temp = [-9999, 25, 30, 35, 9999]
labels_temp = ['<25', '25 to 30', '30 to 35', '>35']
data['temp_class'] = pd.cut(data['temp'], bins=bins_temp, labels=labels_temp)

# bin 'stp' column
bins_stp = [-9999, 980, 990, 1000, 9999]
labels_stp = ['<980', '980 to 990', '990 to 1000', '>1000']
data['stp_class'] = pd.cut(data['stp'], bins=bins_stp, labels=labels_stp)

# bin 'hmdy' column
bins_hmdy = [-9999, 25, 50, 75, 9999]
labels_hmdy = ['<25', '25 to 50', '50 to 75', '>75']
data['hmdy_class'] = pd.cut(data['hmdy'], bins=bins_hmdy, labels=labels_hmdy)

# bin 'prcp' column
bins_prcp = [-9999, 0.1, 1, 10, 9999]
labels_prcp = ['<0.1', '0.1 to 1', '1 to 10', '>10']
data['prcp_class'] = pd.cut(data['prcp'], bins=bins_prcp, labels=labels_prcp)

# bin 'wdct' column
bins_wdct = [-1, 90, 180, 270, 361]
labels_wdct = ['N', 'E', 'S', 'W']
data['wdct_class'] = pd.cut(data['wdct'], bins=bins_wdct, labels=labels_wdct)

# bin 'wdsp' column
bins_wdsp = [-9999, 5, 10, 15, 9999]
labels_wdsp = ['<5', '5 to 10', '10 to 15', '>15']
data['wdsp_class'] = pd.cut(data['wdsp'], bins=bins_wdsp, labels=labels_wdsp)


In [50]:
# create transition matrix for 'temp_class' column
temp_transition_matrix = pd.crosstab(data['temp_class'].shift(), data['temp_class'], normalize='index').values

# create transition matrix for 'stp_class' column
stp_transition_matrix = pd.crosstab(data['stp_class'].shift(), data['stp_class'], normalize='index').values

# create transition matrix for 'hmdy_class' column
hmdy_transition_matrix = pd.crosstab(data['hmdy_class'].shift(), data['hmdy_class'], normalize='index').values

# create transition matrix for 'prcp_class' column
prcp_transition_matrix = pd.crosstab(data['prcp_class'].shift(), data['prcp_class'], normalize='index').values

# create transition matrix for 'wdct_class' column
wdct_transition_matrix = pd.crosstab(data['wdct_class'].shift(), data['wdct_class'], normalize='index').values

# create transition matrix for 'wdsp_class' column
wdsp_transition_matrix = pd.crosstab(data['wdsp_class'].shift(), data['wdsp_class'], normalize='index').values


In [51]:
print(temp_transition_matrix)

[[9.10335590e-01 8.94796149e-02 1.81321269e-04 3.47358754e-06]
 [1.22621134e-01 8.59612271e-01 1.77407918e-02 2.58027030e-05]
 [1.05261675e-02 2.54347152e-01 7.27897867e-01 7.22881380e-03]
 [5.62983814e-03 3.65939479e-02 3.41308937e-01 6.16467277e-01]]


In [52]:
# print transition matrix for 'temp_class' column
temp_data = pd.DataFrame(temp_transition_matrix, columns=labels_temp, index=labels_temp)
print("Transition matrix for 'temp_class' column:")
print(temp_data)

# print transition matrix for 'stp_class' column
stp_data = pd.DataFrame(stp_transition_matrix, columns=labels_stp, index=labels_stp)
print("Transition matrix for 'stp_class' column:")
print(stp_data)

# print transition matrix for 'hmdy_class' column
hmdy_data = pd.DataFrame(hmdy_transition_matrix, columns=labels_hmdy, index=labels_hmdy)
print("Transition matrix for 'hmdy_class' column:")
print(hmdy_data)

# print transition matrix for 'prcp_class' column
prcp_data = pd.DataFrame(prcp_transition_matrix, columns=labels_prcp, index=labels_prcp)
print("Transition matrix for 'prcp_class' column:")
print(prcp_data)

# print transition matrix for 'wdct_class' column
wdct_data = pd.DataFrame(wdct_transition_matrix, columns=labels_wdct, index=labels_wdct)
print("Transition matrix for 'wdct_class' column:")
print(wdct_data)

# print transition matrix for 'wdsp_class' column
wdsp_data = pd.DataFrame(wdsp_transition_matrix, columns=labels_wdsp, index=labels_wdsp)
print("Transition matrix for 'wdsp_class' column:")
print(wdsp_data)


Transition matrix for 'temp_class' column:
               <25  25 to 30  30 to 35       >35
<25       0.910336  0.089480  0.000181  0.000003
25 to 30  0.122621  0.859612  0.017741  0.000026
30 to 35  0.010526  0.254347  0.727898  0.007229
>35       0.005630  0.036594  0.341309  0.616467
Transition matrix for 'stp_class' column:
                 <980  980 to 990  990 to 1000     >1000
<980         0.992171    0.007766     0.000046  0.000016
980 to 990   0.043591    0.913869     0.042361  0.000180
990 to 1000  0.000157    0.047268     0.894975  0.057600
>1000        0.000061    0.000025     0.022901  0.977013
Transition matrix for 'hmdy_class' column:
               <25  25 to 50  50 to 75       >75
<25       0.770995  0.213123  0.013315  0.002567
25 to 50  0.011425  0.791265  0.186371  0.010939
50 to 75  0.000098  0.042007  0.794783  0.163112
>75       0.000037  0.000577  0.148820  0.850566
Transition matrix for 'prcp_class' column:
              <0.1  0.1 to 1   1 to 10       >10
<0.1 

In [53]:
row_index = labels_temp.index('25-30')
row = temp_transition_matrix[row_index]
print(row)

ValueError: '25-30' is not in list

In [ ]:
# # create a dictionary to store occurrence counts for each variable's classes
# occurrence_counts = {
#     'temp_class': {},
#     'stp_class': {},
#     'hmdy_class': {},
#     'prcp_class': {},
#     'wdct_class': {},
#     'wdsp_class': {}
# }

# # count occurrences of each class
# for index, row in data.iterrows():
#     occurrence_counts['temp_class'][row['temp_class']] = occurrence_counts['temp_class'].get(row['temp_class'], 0) + 1
#     occurrence_counts['stp_class'][row['stp_class']] = occurrence_counts['stp_class'].get(row['stp_class'], 0) + 1
#     occurrence_counts['hmdy_class'][row['hmdy_class']] = occurrence_counts['hmdy_class'].get(row['hmdy_class'], 0) + 1
#     occurrence_counts['prcp_class'][row['prcp_class']] = occurrence_counts['prcp_class'].get(row['prcp_class'], 0) + 1
#     occurrence_counts['wdct_class'][row['wdct_class']] = occurrence_counts['wdct_class'].get(row['wdct_class'], 0) + 1
#     occurrence_counts['wdsp_class'][row['wdsp_class']] = occurrence_counts['wdsp_class'].get(row['wdsp_class'], 0) + 1

# # convert occurrence counts to probability matrix
# total_samples = len(data)
# for variable in occurrence_counts.keys():
#     for class_label, count in occurrence_counts[variable].items():
#         occurrence_counts[variable][class_label] = count / total_samples

# # print occurrence probability matrix for each variable
# for variable in occurrence_counts.keys():
#     print("Occurrence probability matrix for '{}' column:".format(variable))
#     print(pd.DataFrame.from_dict(occurrence_counts[variable], orient='index', columns=['Probability']))
#     print('\n')


In [54]:
# create a dictionary to store the transition probability matrix for each variable
transition_matrices = {
    'temp_class': temp_transition_matrix,
    'stp_class': stp_transition_matrix,
    'hmdy_class': hmdy_transition_matrix,
    'prcp_class': prcp_transition_matrix,
    'wdct_class': wdct_transition_matrix,
    'wdsp_class': wdsp_transition_matrix
}

var_label = {
    'temp_class': labels_temp,
    'stp_class': labels_stp,
    'hmdy_class': labels_hmdy,
    'prcp_class': labels_prcp,
    'wdct_class': labels_wdct,
    'wdsp_class': labels_wdsp
}
# set initial values
initial_values = {
    'temp_class': data.iloc[-1]['temp_class'],
    'stp_class': data.iloc[-1]['stp_class'],
    'hmdy_class': data.iloc[-1]['hmdy_class'],
    'prcp_class': data.iloc[-1]['prcp_class'],
    'wdct_class': data.iloc[-1]['wdct_class'],
    'wdsp_class': data.iloc[-1]['wdsp_class']
}
# create a dictionary to store the occurrence probability matrix for each variable
occurrence_matrices = {
    'temp_class': occurrence_counts['temp_class'],
    'stp_class': occurrence_counts['stp_class'],
    'hmdy_class': occurrence_counts['hmdy_class'],
    'prcp_class': occurrence_counts['prcp_class'],
    'wdct_class': occurrence_counts['wdct_class'],
    'wdsp_class': occurrence_counts['wdsp_class']
}



In [55]:
# set number of steps to predict
num_steps = 486  # number of rows from 1st Jan 2020 to 30th April 2021

# create an empty DataFrame to store the predicted values
predicted_df = pd.DataFrame(columns=['date', 'temp_class', 'stp_class', 'hmdy_class', 'prcp_class', 'wdct_class', 'wdsp_class'])

# predict values
for i in range(num_steps):
    # store the predicted values in a dictionary
    predicted_values = {
        'date': (pd.Timestamp('2020-01-01') + pd.Timedelta(days=i)).strftime('%Y-%m-%d'),
        'temp_class': initial_values['temp_class'],
        'stp_class': initial_values['stp_class'],
        'hmdy_class': initial_values['hmdy_class'],
        'prcp_class': initial_values['prcp_class'],
        'wdct_class': initial_values['wdct_class'],
        'wdsp_class': initial_values['wdsp_class']
    }
    # add the predicted values to the DataFrame
    predicted_df = pd.concat([predicted_df, pd.DataFrame(predicted_values, index=[0])], ignore_index=True)
    # update the initial values for the next step
    new_values = {}
    for variable in initial_values.keys():
        prev_class = initial_values[variable]
        tra_mat = transition_matrices[variable]
        row_index = var_label[variable].index(prev_class)
        transition_probs = tra_mat[row_index]
        new_class = str(np.random.choice(var_label[variable], p=transition_probs))
        if variable == 'prcp_class':
            print(new_class)
        new_values[variable] = new_class
    initial_values = new_values

# write the predicted values to a CSV file
predicted_df.to_csv('predicted_weather.csv', index=False)

<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
1 to 10
1 to 10
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
<0.1
<0.1
<0.1
0.1 to 1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
1 to 10
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
1 to 10
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
<0.1
1 to 10
<0.1
<0.1
<0.1
0.1 to 1
0.1 to 1
0.1 to 1
1 to 10
<0.1
<0.1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
0.1 to 1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.1
<0.

In [ ]:
matrix = []

In [ ]:
print(initial_values['hmdy_class'])